'use client';
import { useEffect,useState } from 'react';

type Admin={id:string;name:string;email:string;role:'MASTER_ADMIN'|'ORGANIZER'};
export default function RoleChangePage(){
 const[users,setUsers]=useState<Admin[]>([]),[target,setTarget]=useState(''),[toRole,setToRole]=useState<'MASTER_ADMIN'|'ORGANIZER'>('ORGANIZER'),[password,setPassword]=useState(''),[requestId,setRequestId]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/admin/role-change',{cache:'no-store'}).then(r=>r.json()).then(d=>setUsers(d.users||[])).catch(()=>setError('Could not load admin accounts.'))},[]);
 const selected=users.find(x=>x.id===target);
 async function request(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/role-change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetUserId:target,toRole,password})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not start verification.');setRequestId(d.requestId);setMessage('Verification code sent to the current Master Admin email. It expires in 10 minutes.');setPassword('')}catch(e){setError(e instanceof Error?e.message:'Could not start verification.')}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError('');try{const r=await fetch('/api/admin/role-change/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,code})});const d=await r.json();if(!r.ok)throw Error(d.error||'Verification failed.');setMessage('Role changed successfully. The target account must sign in again.');setRequestId('');setCode('');setTarget('');const rr=await fetch('/api/admin/role-change',{cache:'no-store'});const dd=await rr.json();setUsers(dd.users||[])}catch(e){setError(e instanceof Error?e.message:'Verification failed.')}finally{setBusy(false)}}
 return <div className="main"><div className="page-title"><div><p className="eyebrow">SOCIETY • SECURITY</p><h1>Role Change Verification / રોલ બદલાવ ચકાસણી</h1><p>Role changes require current Master Admin password verification and a one-time email code.</p></div></div><div className="card" style={{maxWidth:760}}><h2>Start verified role change</h2><p className="section-subtitle">Resident OWNER accounts are never changed through this workflow.</p>{error&&<p className="login-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!requestId?<><label className="field-label">Target admin</label><select className="input" value={target} onChange={e=>{setTarget(e.target.value);const u=users.find(x=>x.id===e.target.value);if(u)setToRole(u.role==='MASTER_ADMIN'?'ORGANIZER':'MASTER_ADMIN')}}><option value="">Select admin account</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email} · {u.role}</option>)}</select>{selected&&<><label className="field-label">New role</label><select className="input" value={toRole} onChange={e=>setToRole(e.target.value as any)}><option value="ORGANIZER">ORGANIZER / Sub Admin</option><option value="MASTER_ADMIN">MASTER_ADMIN</option></select><label className="field-label">Current Master Admin password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/><button className="btn btn-primary" disabled={busy||!password} onClick={request}>{busy?'Sending…':'Send verification code'}</button></>}</>:<><label className="field-label">6-digit verification code</label><input className="input" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} autoComplete="one-time-code"/><button className="btn btn-primary" disabled={busy||code.length!==6} onClick={verify}>{busy?'Verifying…':'Verify & change role'}</button></>}</div></div>
}