'use client';
import {useEffect,useState} from 'react';
type Bill={id:string;type:string;amountPaise:string;vendor?:string|null;category?:string|null;date:string;paymentMethod?:string|null;notes?:string|null;propertyUnitId?:string|null;propertyUnit?:{label:string;property:{name:string;propertyNumber:string;block?:string|null}}|null;fileUrl?:string|null};
const money=(p:string)=>'₹ '+(Number(p)/100).toLocaleString('en-IN',{minimumFractionDigits:2});
export default function BillsPage(){
 const [rows,setRows]=useState<Bill[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/bills').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to load bills');setRows(x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const due=rows.filter(x=>x.type==='INVOICE');
 return <main className="main resident-bills-page">
  <div className="page-title"><div><p className="eyebrow">MY SOCIETY • FINANCE</p><h1>Bills / મારા બિલ</h1><p>તમારા યુનિટ સાથે જોડાયેલા બિલ અને દસ્તાવેજો</p></div><span className="page-meta">{rows.length} records</span></div>
  {error&&<div className="login-error">{error}</div>}
  <section className="grid bill-stats"><div className="card stat-card"><span className="stat-label">My Bills</span><strong className="stat-value">{rows.length}</strong><small>Unit-linked records</small></div><div className="card stat-card"><span className="stat-label">Invoice Records</span><strong className="stat-value">{due.length}</strong><small>Review with society</small></div></section>
  <section className="card bill-note"><strong>Secure financial records</strong><p>Only bills linked to your registered society unit are shown here.</p><a className="btn btn-primary" href="/payments">Make a Payment →</a></section>
  {loading?<div className="card empty-state">Loading bills…</div>:rows.length===0?<div className="card empty-state">No bills are currently linked to your unit.</div>:<section className="bill-list">{rows.map(b=><article className="card bill-card" key={b.id}><div className="bill-main"><div className="bill-top"><span className="badge">{b.type}</span><time>{new Date(b.date).toLocaleDateString('en-IN')}</time></div><h2>{b.category||b.vendor||'Society Bill'}</h2><p>{b.vendor||'Society financial document'}{b.propertyUnit&&' • '+b.propertyUnit.property.name+' '+b.propertyUnit.label}</p>{b.notes&&<small>{b.notes}</small>}</div><div className="bill-side"><strong>{money(b.amountPaise)}</strong>{b.fileUrl&&<a className="btn btn-secondary" href={b.fileUrl} target="_blank" rel="noreferrer">View Document</a>}<a className="btn btn-secondary" href="/payments">Pay / View Payment</a></div></article>)}</section>}
  <style>{".bill-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.bill-note{border-top:3px solid var(--gold);display:flex;align-items:center;gap:16px;justify-content:space-between}.bill-note p{margin:4px 0;color:var(--muted);font-size:13px}.bill-list{display:grid;gap:14px}.bill-card{border-left:3px solid var(--gold);display:flex;justify-content:space-between;gap:20px}.bill-top{display:flex;gap:10px;align-items:center;color:var(--muted);font-size:12px}.bill-main h2{margin:10px 0 4px;color:var(--maroon);font-size:19px}.bill-main p{margin:0;color:var(--muted)}.bill-main small{display:block;margin-top:8px;color:var(--muted)}.bill-side{display:flex;flex-direction:column;align-items:flex-end;gap:8px;min-width:150px}.bill-side strong{font:800 20px var(--font-inter),sans-serif;color:var(--maroon)}@media(max-width:650px){.bill-stats{grid-template-columns:1fr}.bill-note,.bill-card{flex-direction:column;align-items:flex-start}.bill-side{align-items:flex-start;min-width:0;width:100%}.bill-side .btn{width:100%;text-align:center}}"} </style>
 </main>
}