'use client';
import {useEffect,useState} from 'react';
type Bill={id:string;type:string;amountPaise:string;vendor?:string|null;category?:string|null;date:string;paymentMethod?:string|null;notes?:string|null;propertyUnitId?:string|null;propertyUnit?:{label:string;property:{name:string;propertyNumber:string;block?:string|null}}|null;fileUrl?:string|null;paymentStatus?:string};
type ReceiptPayment={id:string;amountPaise:string;createdAt:string;verifiedAt?:string|null;transactionId?:string|null;receiptNumber?:string|null;billId?:string|null};
const money=(p:string)=>'₹ '+(Number(p)/100).toLocaleString('en-IN',{minimumFractionDigits:2});
export default function BillsPage(){
 const [rows,setRows]=useState<Bill[]>([]),[receipts,setReceipts]=useState<ReceiptPayment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[receiptId,setReceiptId]=useState('');
 useEffect(()=>{fetch('/api/bills').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to load bills');setRows(x.bills||[]);setReceipts(x.receiptPayments||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 function payBill(b:Bill){window.location.href=`/payments?billId=${encodeURIComponent(b.id)}&amount=${encodeURIComponent((Number(b.amountPaise)/100).toFixed(2))}`)}
 async function downloadReceipt(id:string){setReceiptId(id);setError('');try{const r=await fetch(`/api/payments/receipt?paymentId=${encodeURIComponent(id)}`);const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to prepare receipt');if(x.url)window.open(x.url,'_blank','noopener,noreferrer');else throw new Error('Receipt download unavailable')}catch(e){setError(e instanceof Error?e.message:'Unable to prepare receipt')}finally{setReceiptId('')}}
 const due=rows.filter(x=>x.type==='INVOICE');
 return <main className="main resident-bills-page">
  <div className="page-title"><div><p className="eyebrow">MY SOCIETY • FINANCE</p><h1>Bills / મારા બિલ</h1><p>તમારા યુનિટ સાથે જોડાયેલા બિલ અને દસ્તાવેજો</p></div><span className="page-meta">{rows.length} records</span></div>
  {error&&<div className="login-error">{error}</div>}
  <section className="grid bill-stats"><div className="card stat-card"><span className="stat-label">My Bills</span><strong className="stat-value">{rows.length}</strong><small>Unit-linked records</small></div><div className="card stat-card"><span className="stat-label">Verified Receipts</span><strong className="stat-value">{receipts.length}</strong><small>Downloadable payment records</small></div></section>
  <section className="card bill-note"><strong>Secure financial records</strong><p>Only bills linked to your registered society unit are shown here.</p><a className="btn btn-primary" href="/payments">Make a Payment</a></section>
  {loading?<div className="card empty-state">Loading bills…</div>:rows.length===0?<div className="card empty-state">No bills are currently linked to your unit.</div>:<section className="bill-list">{rows.map(b=><article className="card bill-card" key={b.id}><div className="bill-main"><div className="bill-top"><span className="badge">{b.type}</span><span className={`bill-status bill-status-${b.paymentStatus||'UNPAID'}`}>{b.paymentStatus||'UNPAID'}</span><time>{new Date(b.date).toLocaleDateString('en-IN')}</time></div><h2>{b.category||b.vendor||'Society Bill'}</h2><p>{b.vendor||'Society financial document'}{b.propertyUnit&&' • '+b.propertyUnit.property.name+' '+b.propertyUnit.label}</p>{b.notes&&<small>{b.notes}</small>}</div><div className="bill-side"><strong>{money(b.amountPaise)}</strong>{b.fileUrl&&<a className="btn btn-secondary" href={b.fileUrl} target="_blank" rel="noreferrer">View Document</a>}<a className="btn btn-secondary" href="/payments">Pay / View Payment</a></div>{b.paymentStatus!=='PAID'&&<button className="btn btn-primary" onClick={()=>payBill(b)}>Pay This Bill</button>}{b.paymentStatus==='PAID'&&<span className="paid-note">Payment received</span>}</article>)}</section>}
  <section className="card receipt-section"><div className="page-title"><div><p className="eyebrow">PAYMENT HISTORY</p><h2>My Payment Receipts</h2><p>Verified payments ke receipts yahan se download karein.</p></div></div>{receipts.length===0?<p className="empty-state">No verified receipts yet.</p>:<div className="receipt-list">{receipts.map(r=><article className="receipt-row" key={r.id}><div><strong>{r.receiptNumber||'Receipt pending'}</strong><p>{new Date(r.verifiedAt||r.createdAt).toLocaleDateString('en-IN')} • {money(r.amountPaise)}</p>{r.transactionId&&<small>UTR: {r.transactionId}</small>}</div><button className="btn btn-secondary" disabled={receiptId===r.id} onClick={()=>downloadReceipt(r.id)}>{receiptId===r.id?'Preparing…':'Download Receipt'}</button></article>)}</div>}</section>
  <style>{".bill-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.bill-note{border-top:3px solid var(--gold);display:flex;align-items:center;gap:16px;justify-content:space-between}.bill-note p{margin:4px 0;color:var(--muted);font-size:13px}.bill-list{display:grid;gap:14px}.bill-card{border-left:3px solid var(--gold);display:flex;justify-content:space-between;gap:20px}.bill-top{display:flex;gap:10px;align-items:center;color:var(--muted);font-size:12px}.bill-main h2{margin:10px 0 4px;color:var(--maroon);font-size:19px}.bill-main p{margin:0;color:var(--muted)}.bill-main small{display:block;margin-top:8px;color:var(--muted)}.bill-side{display:flex;flex-direction:column;align-items:flex-end;gap:8px;min-width:150px}.bill-status{padding:4px 9px;border-radius:999px;font-size:11px;font-weight:800}.bill-status-PAID{background:#e9f5ec;color:#216a35}.bill-status-PENDING{background:var(--gold-highlight);color:var(--maroon)}.bill-status-UNPAID{background:#f7eee8;color:var(--muted)}.paid-note{font-weight:800;color:#216a35;padding:10px 0}.bill-side strong{font:800 20px var(--font-inter),sans-serif;color:var(--maroon)}.receipt-section{margin-top:18px}.receipt-list{display:grid;gap:10px}.receipt-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 0;border-top:1px solid var(--border)}.receipt-row p{margin:4px 0;color:var(--muted)}.receipt-row small{color:var(--muted)}@media(max-width:650px){.bill-stats{grid-template-columns:1fr}.bill-note,.bill-card,.receipt-row{flex-direction:column;align-items:flex-start}.bill-side{align-items:flex-start;min-width:0;width:100%}.bill-side .btn,.receipt-row .btn{width:100%;text-align:center}}"}</style>
 </main>
}
