import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireSession } from '@/lib/session';

async function rest<T>(table:string,q:Record<string,string>={},init?:RequestInit){const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');const u=new URL(b+'/rest/v1/'+table);Object.entries(q).forEach(([a,v])=>u.searchParams.set(a,v));const r=await fetch(u,{...init,headers:{apikey:k,Authorization:'Bearer '+k,Accept:'application/json',...(init?.body?{'Content-Type':'application/json','Prefer':'return=representation'}:{}),...(init?.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error('REST');return d as T}
const bucket=()=>process.env.SUPABASE_STORAGE_BUCKET?.trim()||'society-files';
async function sign(path:string,societyId:string){if(!path||/^https?:\/\//.test(path)||path.startsWith('data:'))return path;if(!path.startsWith(`${societyId}/payment-qrs/`))return null;const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');const r=await fetch(b+'/storage/v1/object/sign/'+bucket()+'/'+path,{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600}),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error('SIGN');return b+'/storage/v1'+(d?.signedURL||d?.signedUrl||'')}
function bytesFromBase64(v:string){const raw=atob(v);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function valid(bytes:Uint8Array,ext:string){if(ext==='jpg')return bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(ext==='png')return bytes.length>=8&&Array.from(bytes.slice(0,8)).join(',')==='137,80,78,71,13,10,26,10';if(ext==='webp')return bytes.length>=12&&new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';return false}
async function storeQr(value:string,societyId:string){if(!value)return null;if(!value.startsWith('data:image/'))return value;const m=value.match(/^data:(image\/(jpeg|png|webp));base64,(.+)$/);if(!m)throw Error('INVALID_QR');const ext=m[2]==='jpeg'?'jpg':m[2],bytes=bytesFromBase64(m[3]);if(!bytes.length||bytes.length>5*1024*1024||!valid(bytes,ext))throw Error('INVALID_QR');const path=`${societyId}/payment-qrs/${crypto.randomUUID()}.${ext}`;const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');const r=await fetch(b+'/storage/v1/object/'+bucket()+'/'+path,{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':m[1]},body:bytes});if(!r.ok)throw Error('UPLOAD');return path}
const upiPattern=/^[a-zA-Z0-9._-]{2,100}@[a-zA-Z0-9.-]{2,50}$/;
const schema=z.object({displayName:z.string().trim().min(2).max(100),upiId:z.string().trim().max(100).optional().or(z.literal('')),qrImageUrl:z.string().max(4000000).optional().or(z.literal('')),purpose:z.string().trim().min(2).max(200),instructions:z.string().trim().max(500).optional().or(z.literal('')),ownerUserId:z.string().optional().or(z.literal('')),amountPaise:z.coerce.number().int().positive()}).superRefine((value,ctx)=>{if(value.upiId&& !upiPattern.test(value.upiId))ctx.addIssue({code:z.ZodIssueCode.custom,path:['upiId'],message:'Invalid UPI ID format.'});});
export async function GET(){try{const s=await requireSession();const accounts=await rest<any[]>('PaymentAccount',{select:'id,displayName,upiId,qrImageUrl,purpose,instructions,ownerUserId,amountPaise',societyId:'eq.'+s.societyId,status:'eq.ACTIVE',order:'createdAt.asc'});return NextResponse.json({accounts:await Promise.all(accounts.map(async a=>({...a,qrImageUrl:a.qrImageUrl?await sign(a.qrImageUrl,s.societyId):null,amountPaise:a.amountPaise==null?null:String(a.amountPaise)})))});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Server error'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500})}}
export async function POST(req:Request){try{const s=await requireSession();if(s.role!=='MASTER_ADMIN')throw Error('FORBIDDEN');const body=schema.parse(await req.json());const normalizedUpi=body.upiId?body.upiId.toLowerCase():'';if(normalizedUpi){const duplicate=(await rest<any[]>('PaymentAccount',{select:'id',societyId:'eq.'+s.societyId,status:'eq.ACTIVE',upiId:'ilike.'+normalizedUpi,limit:'1'}))[0];if(duplicate)return NextResponse.json({error:'This UPI ID is already registered.'},{status:409})}const ownerUserId=body.ownerUserId||s.id;if(body.ownerUserId){const owner=(await rest<any[]>('User',{select:'id',id:'eq.'+body.ownerUserId,societyId:'eq.'+s.societyId,role:'in.(MASTER_ADMIN,ORGANIZER)',status:'eq.ACTIVE'}))[0];if(!owner)return NextResponse.json({error:'Invalid payment account owner.'},{status:400})}const qrImageUrl=await storeQr(body.qrImageUrl||'',s.societyId);const now=new Date().toISOString();const account=(await rest<any[]>('PaymentAccount',{select:'*'},{method:'POST',body:JSON.stringify({id:crypto.randomUUID(),societyId:s.societyId,ownerUserId,displayName:body.displayName,upiId:normalizedUpi||null,qrImageUrl,purpose:body.purpose,instructions:body.instructions||null,amountPaise:body.amountPaise,createdAt:now,updatedAt:now})}))[0];await rest('AuditLog',{}, {method:'POST',body:JSON.stringify({id:crypto.randomUUID(),userId:s.id,action:'CREATE',module:'PAYMENT_ACCOUNT',recordId:account.id,details:`Created payment account ${account.displayName}`,createdAt:now})});return NextResponse.json({account},{status:201})}catch(e){const status=e instanceof z.ZodError?400:e instanceof Error&&e.message==='FORBIDDEN'?403:500;return NextResponse.json({error:status===400?'Invalid payment account details.':status===403?'Master Admin access required':'Server error'},{status})}}
export async function DELETE(req:Request){try{const s=await requireSession();if(s.role!=='MASTER_ADMIN')throw Error('FORBIDDEN');const body=await req.json().catch(()=>null);const accountId=typeof body?.accountId==='string'?body.accountId.trim():'';if(!accountId)return NextResponse.json({error:'Payment account id is required.'},{status:400});const account=(await rest<any[]>('PaymentAccount',{select:'id,displayName',id:'eq.'+accountId,societyId:'eq.'+s.societyId,status:'eq.ACTIVE',limit:'1'}))[0];if(!account)return NextResponse.json({error:'Payment account not found.'},{status:404});const now=new Date().toISOString();await rest('PaymentAccount',{id:'eq.'+accountId,societyId:'eq.'+s.societyId},{method:'PATCH',body:JSON.stringify({status:'INACTIVE',updatedAt:now})});await rest('AuditLog',{}, {method:'POST',body:JSON.stringify({id:crypto.randomUUID(),userId:s.id,action:'DELETE',module:'PAYMENT_ACCOUNT',recordId:accountId,details:`Deleted payment account ${account.displayName}`,createdAt:now})});return NextResponse.json({ok:true});}catch(e){const status=e instanceof Error&&e.message==='FORBIDDEN'?403:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500;return NextResponse.json({error:status===403?'Master Admin access required':status===401?'Unauthorized':'Server error'},{status})}}