'use client';
import { useEffect, useState } from 'react';
type Flat = { id: string; flatNumber: string; ownerName: string | null; mobile: string | null; email: string | null; status: 'ACTIVE' | 'INACTIVE'; signupEnabled: boolean };
export default function Flats() {
  const [rows,setRows]=useState<Flat[]>([]); const [form,setForm]=useState({flatNumber:'',ownerName:'',mobile:'',email:'',status:'ACTIVE',signupEnabled:false}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [query,setQuery]=useState('');
  async function load(){setLoading(true); const r=await fetch('/api/admin/flats',{cache:'no-store'}); if(r.ok)setRows(await r.json()); else setError('Organizer access required'); setLoading(false);}
  useEffect(()=>{load();},[]);
  async function save(e:React.FormEvent){e.preventDefault();setError('');setSaving(true);try{const r=await fetch('/api/admin/flats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await r.json().catch(()=>({}));if(!r.ok){setError(body.error||'Could not save flat.');return;}setForm({flatNumber:'',ownerName:'',mobile:'',email:'',status:'ACTIVE',signupEnabled:false});await load();}finally{setSaving(false);}}
  async function toggle(row:Flat){setError('');const r=await fetch('/api/admin/flats',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,ownerName:row.ownerName||'',mobile:row.mobile||'',email:row.email||'',status:row.status,signupEnabled:!row.signupEnabled})});const body=await r.json().catch(()=>({}));if(!r.ok){setError(body.error||'Could not update signup access.');return;}setRows(rows.map(x=>x.id===row.id?{...x,signupEnabled:!row.signupEnabled}:x));}
  const filtered=rows.filter(x=>[x.flatNumber,x.ownerName,x.mobile,x.email].some(v=>(v||'').toLowerCase().includes(query.toLowerCase())));
  return <div className="main"><div className="page-title"><div><p className="eyebrow">SOCIETY • MEMBERS</p><h1>Flats & Owners / ફ્લેટ અને સભ્યો</h1><p>Pre-register owner details and control who can create a Flat Owner account.</p></div><div className="stat-card"><span className="stat-label">Registered Flats</span><strong>{rows.length}</strong></div></div>
    <div className="card" style={{marginBottom:18}}><div className="section-heading"><div><h2>Register Flat / ફ્લેટ નોંધણી</h2><p>Owner signup requires a registered email or mobile and explicit signup access.</p></div></div><form onSubmit={save} className="form-grid">
      <div className="field"><label htmlFor="flatNumber">Flat Number</label><input id="flatNumber" className="input" required value={form.flatNumber} onChange={e=>setForm({...form,flatNumber:e.target.value})} placeholder="A-101" /></div>
      <div className="field"><label htmlFor="ownerName">Owner Name</label><input id="ownerName" className="input" value={form.ownerName} onChange={e=>setForm({...form,ownerName:e.target.value})} placeholder="Full name" /></div>
      <div className="field"><label htmlFor="mobile">Registered Mobile</label><input id="mobile" className="input" inputMode="tel" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} placeholder="98765 43210" /></div>
      <div className="field"><label htmlFor="email">Registered Email</label><input id="email" className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="owner@example.com" /></div>
      <div className="field"><label htmlFor="status">Status</label><select id="status" className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></div>
      <label className="field" style={{display:'flex',alignItems:'center',gap:10}}><span>Owner signup access</span><input type="checkbox" checked={form.signupEnabled} onChange={e=>setForm({...form,signupEnabled:e.target.checked})} style={{width:20,height:20}} /> <small>Allow signup</small></label>
      <button className="btn btn-primary" disabled={saving}>{saving?'Saving…':'Add Flat / Owner'}</button></form>{error&&<p className="login-error" role="alert">{error}</p>}</div>
    <div className="card"><div className="section-heading"><div><h2>Flat Directory</h2><p>{rows.length} registered flat{rows.length===1?'':'s'}</p></div><input className="input" style={{maxWidth:280}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search flat or owner…" aria-label="Search flats" /></div>
      <div className="table-wrap"><table className="table"><thead><tr><th>Flat</th><th>Owner</th><th>Mobile</th><th>Email</th><th>Status</th><th>Signup</th></tr></thead><tbody>{loading&&<tr><td colSpan={6}>Loading flats…</td></tr>}{!loading&&filtered.map(x=><tr key={x.id}><td><b>{x.flatNumber}</b></td><td>{x.ownerName||'—'}</td><td>{x.mobile||'—'}</td><td>{x.email||'—'}</td><td><span className="badge">{x.status}</span></td><td><button type="button" className="btn" onClick={()=>toggle(x)} aria-label={`${x.signupEnabled?'Disable':'Enable'} signup for ${x.flatNumber}`}>{x.signupEnabled?'Enabled':'Enable'}</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={6}>No flats found.</td></tr>}</tbody></table></div></div></div>;
}
