"use client";
import { useEffect,useMemo,useState } from "react";
type Unit={id:string;label:string;floorNumber:number;floorLabel:string;residentType:"OWNER"|"TENANT"|null;ownerName:string|null;ownerMobile:string|null;ownerEmail:string|null;signupEnabled?:boolean;residentUserId?:string|null};
type Property={id:string;type:"APARTMENT"|"TENAMENT";name:string;propertyNumber:string;block:string|null;units:Unit[]};
const blocks=["A","B","C"],flats=Array.from({length:26},(_,i)=>i+1);
export default function PropertiesPage(){const[properties,setProperties]=useState<Property[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<{property:Property;unit?:Unit}|null>(null);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/properties",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load properties");setProperties(d.properties||[])}catch(e:any){setMessage(e.message||"Unable to load properties")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 async function setup(kind:"APARTMENT"|"TENAMENT"){if(!confirm(kind==="APARTMENT"?"Create Sarang Apartment Blocks A, B, C with 26 flats in each block?":"Create Pramukhpark Society Tenaments 1–27? Floors will be added separately."))return;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/properties/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({setup:kind})}),d=await r.json();if(!r.ok)throw Error(d.error||"Setup failed");setMessage(kind==="APARTMENT"?`Apartment ready: ${d.apartmentUnits||78} flats.`:`Pramukhpark ready: ${d.tenaments||27} tenaments. Add floors individually.`);await load()}catch(e:any){setMessage(e.message||"Setup failed")}finally{setBusy(false)}}
 const apartments=useMemo(()=>properties.filter(p=>p.type==="APARTMENT"),[properties]),tenaments=useMemo(()=>properties.filter(p=>p.type==="TENAMENT").sort((a,b)=>Number(a.propertyNumber)-Number(b.propertyNumber)),[properties]);
 return <main className="main"><div className="page-header"><div><h1>Properties & Units</h1><p>Manage Sarang Apartment and Pramukhpark Society residences.</p></div></div>{message&&<div className="alert">{message}</div>}
 <section className="card"><h2>Initial Property Setup</h2><p>Creates the fixed structure only. Resident accounts are never created automatically.</p><div className="actions"><button className="btn btn-primary" disabled={busy} onClick={()=>setup("APARTMENT")}>{busy?"Working…":"Setup Sarang Apartment · 78 Flats"}</button><button className="btn btn-secondary" disabled={busy} onClick={()=>setup("TENAMENT")}>{busy?"Working…":"Setup Pramukhpark · 27 Tenaments"}</button></div></section>
 <section className="card"><h2>Sarang Apartment</h2>{loading?<p>Loading…</p>:<div className="property-grid">{blocks.map(block=>{const p=apartments.find(x=>x.block===block);return <div className="property-group" key={block}><h3>Block {block}</h3><div className="unit-grid">{flats.map(n=>{const u=p?.units.find(x=>x.label===String(n));return <button key={n} disabled={!u} className={u?"unit-chip":"unit-chip missing"} onClick={()=>u&&setSelected({property:p!,unit:u})} title={u?`${u.residentType||"Unassigned"}${u.ownerName?` · ${u.ownerName}`:""}`:"Flat not created"}>{n}</button>})}</div></div>})}</div>}</section>
 <section className="card"><h2>Pramukhpark Society</h2>{loading?<p>Loading…</p>:<div className="property-grid">{tenaments.map(p=><button key={p.id} className="property-row" onClick={()=>setSelected({property:p})}><strong>Tenament {p.propertyNumber}</strong><span>{p.units.length} floor{p.units.length===1?"":"s"}</span></button>)}</div>}</section>
 {selected&&<UnitManager property={selected.property} initialUnit={selected.unit} onClose={()=>setSelected(null)} onChanged={load}/>}</main>}
function UnitManager({property,initialUnit,onClose,onChanged}:{property:Property;initialUnit?:Unit;onClose:()=>void;onChanged:()=>void}){const[unit,setUnit]=useState<Unit|undefined>(initialUnit),[floorLabel,setFloorLabel]=useState("Ground"),[floorNumber,setFloorNumber]=useState(0),[type,setType]=useState<"OWNER"|"TENANT">(initialUnit?.residentType||"OWNER"),[name,setName]=useState(initialUnit?.ownerName||""),[mobile,setMobile]=useState(initialUnit?.ownerMobile||""),[email,setEmail]=useState(initialUnit?.ownerEmail||""),[signup,setSignup]=useState(initialUnit?.signupEnabled??false),[busy,setBusy]=useState(false);
 async function save(){if(!unit)return;if(!mobile.trim())return alert("Mobile number is required.");setBusy(true);try{const r=await fetch(`/api/admin/properties/${property.id}/units/${unit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({residentType:type,name:name||null,mobile,email,signupEnabled:signup,residentUserId:unit.residentUserId||null})}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save resident");setUnit(d.unit);onChanged();alert("Resident details saved.")}catch(e:any){alert(e.message||"Unable to save resident")}finally{setBusy(false)}}
 async function addFloor(){if(!mobile.trim())return alert("Mobile number is required.");setBusy(true);try{const r=await fetch(`/api/admin/properties/${property.id}/units`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:floorLabel,floorNumber,floorLabel,residentType:type,ownerName:name||null,ownerMobile:mobile,ownerEmail:email||null})}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to add floor");onChanged();alert("Floor added")}catch(e:any){alert(e.message||"Unable to add floor")}finally{setBusy(false)}}
 return <div className="modal-backdrop"><div className="modal card"><div className="modal-header"><div><h2>{property.type==="TENAMENT"?`Tenament ${property.propertyNumber}`:`Block ${property.block} · Flat ${unit?.label||""}`}</h2><p>{property.name}</p></div><button className="icon-btn" onClick={onClose}>×</button></div>
 <h3>{unit?"Resident Assignment":"Floors"}</h3>{property.units.length>0&&<div className="floor-list">{property.units.map(u=><button className={`floor-row ${unit?.id===u.id?"selected-row":""}`} key={u.id} onClick={()=>{setUnit(u);setType(u.residentType||"OWNER");setName(u.ownerName||"");setMobile(u.ownerMobile||"");setEmail(u.ownerEmail||"");setSignup(u.signupEnabled??false)}}><span><strong>{u.label}</strong> · {u.floorLabel} · {u.residentType||"Unassigned"}</span><span>{u.ownerName||"No resident"} · {u.ownerMobile||"No mobile"}</span></button>)}</div>}
 {unit&&<><div className="form-grid"><label>Resident type<select value={type} onChange={e=>setType(e.target.value as any)}><option value="OWNER">Owner</option><option value="TENANT">Tenant / Rental</option></select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Mobile *<input required value={mobile} onChange={e=>setMobile(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><label className="toggle"><input type="checkbox" checked={signup} onChange={e=>setSignup(e.target.checked)}/> Allow resident signup for this unit</label><div className="actions"><button className="btn btn-secondary" onClick={onClose}>Close</button><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save Resident"}</button></div></>}
 {property.type==="TENAMENT"&&<><h3>Add Floor</h3><div className="form-grid"><label>Floor label<input value={floorLabel} onChange={e=>setFloorLabel(e.target.value)} placeholder="Ground / 1st / 2nd / 3rd"/></label><label>Floor number<input type="number" min="0" value={floorNumber} onChange={e=>setFloorNumber(Number(e.target.value))}/></label></div><div className="actions"><button className="btn btn-primary" disabled={busy} onClick={addFloor}>{busy?"Saving…":"Add Floor"}</button></div></>}</div></div>}
const style=`.property-grid{display:grid;gap:18px}.property-group{padding:16px;border:1px solid #eadfce;border-radius:12px}.unit-grid{display:grid;grid-template-columns:repeat(13,minmax(36px,1fr));gap:8px}.unit-chip,.property-row,.floor-row{border:1px solid #ddcfbd;background:#fffaf2;border-radius:8px;padding:10px;cursor:pointer}.unit-chip.missing{opacity:.4;cursor:not-allowed}.property-row{display:flex;justify-content:space-between;text-align:left;width:100%}.modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.42);display:grid;place-items:center;padding:20px;z-index:50}.modal{width:min(850px,100%);max-height:90vh;overflow:auto}.modal-header{display:flex;justify-content:space-between}.floor-list{display:grid;gap:8px;margin-bottom:20px}.floor-row{display:flex;justify-content:space-between;gap:12px;width:100%;text-align:left}.selected-row{outline:2px solid #a07a35}.icon-btn{border:0;background:transparent;font-size:28px;cursor:pointer}.toggle{display:flex;gap:8px;align-items:center;margin:16px 0}@media(max-width:700px){.unit-grid{grid-template-columns:repeat(6,1fr)}.floor-row{flex-direction:column}}`;if(typeof document!=="undefined"&&!document.getElementById("property-page-style")){const s=document.createElement("style");s.id="property-page-style";s.textContent=style;document.head.appendChild(s)}
