'use client';
import { useEffect, useMemo, useState } from 'react';

type Event={id:string;title:string;gujaratiTitle?:string|null;date:string;time?:string|null;location?:string|null;type?:string|null;description?:string|null;imageUrl?:string|null};
export default function ProgramsPage(){
 const [events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('All');
 useEffect(()=>{fetch('/api/programs').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to load programs');setEvents(Array.isArray(x)?x:[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const types=useMemo(()=>['All',...Array.from(new Set(events.map(e=>e.type).filter(Boolean) as string[]))],[events]);
 const visible=useMemo(()=>filter==='All'?events:events.filter(e=>e.type===filter),[events,filter]);
 return <main className="main programs-page">
  <div className="page-title"><div><p className="eyebrow">COMMUNITY • CALENDAR</p><h1>Programs / કાર્યક્રમો</h1><p>આપણી સોસાયટીના આગામી કાર્યક્રમો અને સમુદાયિક પ્રવૃત્તિઓ</p></div><span className="page-meta">{events.length} programs</span></div>
  {error&&<div className="login-error">{error}</div>}
  <section className="card programs-hero"><div><p className="eyebrow">Madhuli Yuva Group</p><h2>Upcoming Community Programs</h2><p>Stay updated with published society events.</p></div><div className="program-filters">{types.map(t=><button key={t} className={'program-chip '+(filter===t?'active':'')} onClick={()=>setFilter(t)}>{t}</button>)}</div></section>
  {loading?<div className="card empty-state">Loading programs…</div>:visible.length===0?<div className="card empty-state">No published programs available.</div>:<section className="program-grid">{visible.map(e=><article className="card program-card" key={e.id}>{e.imageUrl&&<img src={e.imageUrl} alt={e.gujaratiTitle||e.title}/>}<div className="program-copy"><span className="program-date">{new Date(e.date).toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}</span><span className="program-type">{e.type||'Community'}</span><h2>{e.gujaratiTitle||e.title}</h2>{e.gujaratiTitle&&<small>{e.title}</small>}<p>{e.description||'સમુદાયિક કાર્યક્રમ માટે વધુ વિગતો ટૂંક સમયમાં ઉપલબ્ધ થશે.'}</p><div className="program-meta"><span>🕘 {e.time||'Time to be announced'}</span><span>📍 {e.location||'Society premises'}</span></div></div></article>)}</section>}
  <style>{".programs-hero{border-top:3px solid var(--gold);display:flex;justify-content:space-between;gap:20px;align-items:flex-end}.programs-hero h2{margin:4px 0;color:var(--maroon)}.programs-hero p:last-child{margin:0;color:var(--muted)}.program-filters{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.program-chip{border:1px solid var(--border);background:var(--surface);color:var(--muted);padding:8px 13px;border-radius:999px;cursor:pointer;font:600 12px var(--font-inter),sans-serif}.program-chip.active{background:var(--maroon);border-color:var(--maroon);color:#fff}.program-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.program-card{overflow:hidden;padding:0}.program-card>img{width:100%;aspect-ratio:16/8;object-fit:cover;display:block}.program-copy{padding:17px}.program-date{font:700 12px var(--font-inter),sans-serif;color:var(--maroon)}.program-type{float:right;font:700 10px var(--font-inter),sans-serif;background:var(--soft-surface);padding:5px 8px;border-radius:999px;color:var(--muted)}.program-copy h2{margin:10px 0 3px;color:var(--maroon);font-size:19px}.program-copy small{color:var(--muted)}.program-copy p{color:var(--muted);line-height:1.65;font-size:13px}.program-meta{display:flex;flex-direction:column;gap:7px;border-top:1px solid var(--border);padding-top:12px;font-size:12px;color:var(--ink)}@media(max-width:950px){.program-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.programs-hero{flex-direction:column;align-items:flex-start}.program-filters{justify-content:flex-start}}@media(max-width:600px){.program-grid{grid-template-columns:1fr}.program-copy{padding:14px}}"} </style>
 </main>
}