import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';

type Context={payment:any;owner:any;society:any;event:any;account:any;bill:any};
const W=595,H=842,MAROON=rgb(.35,.04,.04),DARK=rgb(.13,.12,.11),MUTED=rgb(.38,.36,.33);
function config(){const base=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();const bucket=process.env.SUPABASE_STORAGE_BUCKET?.trim()||'society-files';if(!base||!key)throw Error('CONFIG');return{base,key,bucket}}
async function rest<T>(table:string,q:Record<string,string>,init?:RequestInit):Promise<T>{const{base,key}=config();const u=new URL(`${base}/rest/v1/${table}`);Object.entries(q).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json',...(init?.body?{'Content-Type':'application/json',Prefer:'return=representation'}:{}),...(init?.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(String(d?.message||'REST'));return d as T}
function pathParts(path:string){return path.split('/').map(x=>encodeURIComponent(x)).join('/')}
async function upload(path:string,bytes:Uint8Array){const{base,key,bucket}=config();const r=await fetch(`${base}/storage/v1/object/${encodeURIComponent(bucket)}/${pathParts(path)}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/pdf','x-upsert':'true'},body:bytes as unknown as BodyInit,cache:'no-store'});if(!r.ok)throw Error('STORAGE_UPLOAD')}
export async function signReceipt(path:string|null|undefined){if(!path)return null;const{base,key,bucket}=config();const r=await fetch(`${base}/storage/v1/object/sign/${encodeURIComponent(bucket)}/${pathParts(path)}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600}),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error('STORAGE_SIGN');const s=d?.signedURL||d?.signedUrl;return s?(String(s).startsWith('http')?String(s):base+'/storage/v1'+String(s)):null}
async function context(paymentId:string,societyId:string):Promise<Context|null>{const payment=(await rest<any[]>('Payment',{select:'*',id:`eq.${paymentId}`,societyId:`eq.${societyId}`,status:'eq.VERIFIED',limit:'1'}))[0];if(!payment)return null;const[owner,society,event,account,bill]=await Promise.all([rest<any[]>('User',{select:'id,name,email,mobile,flatId,unitId',id:`eq.${payment.ownerUserId}`,limit:'1'}),rest<any[]>('Society',{select:'id,authorizedSignatory,reportFooter',id:`eq.${societyId}`,limit:'1'}),payment.eventId?rest<any[]>('Event',{select:'id,title,gujaratiTitle,date',id:`eq.${payment.eventId}`,limit:'1'}):[],rest<any[]>('PaymentAccount',{select:'id,displayName,purpose',id:`eq.${payment.paymentAccountId}`,limit:'1'}),payment.billId?rest<any[]>('Bill',{select:'id,type,category,date,paymentMethod',id:`eq.${payment.billId}`,limit:'1'}):[]]);return{payment,owner:owner[0]||null,society:society[0]||null,event:event[0]||null,account:account[0]||null,bill:bill[0]||null}}
function clean(v:unknown,f='-'){const s=String(v??'').trim();return s||f}
function money(v:unknown){return`Rs. ${(Number(v||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function dateText(v:unknown){return v?new Date(String(v)).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-'}
function receiptNumber(id:string,verifiedAt:unknown){const year=verifiedAt?new Date(String(verifiedAt)).getFullYear():new Date().getFullYear();return`MYGM-${year}-${id.replace(/[^a-zA-Z0-9]/g,'').slice(-8).toUpperCase()}`}
function method(c:Context){const value=String(c.payment?.paymentMethod||c.payment?.method||c.bill?.paymentMethod||(c.payment?.transactionId?'UPI':'CASH')).toUpperCase();return value==='CASH'?'Cash':value==='UPI'?'UPI':value.replace(/[_-]+/g,' ').replace(/\b\w/g,l=>l.toUpperCase())}
function transaction(c:Context){return method(c)==='Cash'?'Not Applicable (Cash)':clean(c.payment?.transactionId,'Not Submitted')}
function png(bytes:Uint8Array){return bytes.length>7&&bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10}
async function letterhead(pdf:PDFDocument,url:string){const origin=process.env.NEXT_PUBLIC_APP_URL?.trim();const candidates=[origin?new URL('/letterhead,A4.jpg',origin).toString():null,new URL('/letterhead,A4.jpg',url).toString(),'https://raw.githubusercontent.com/jdreality5-crm/madhuli-yuva-group-society/fresh-society-v2/v2/public/letterhead,A4.jpg',origin?new URL('/letterhead.jpg',origin).toString():null,new URL('/letterhead.jpg',url).toString()].filter(Boolean) as string[];for(const candidate of candidates){try{const r=await fetch(candidate,{cache:'no-store'});if(!r.ok)continue;const b=new Uint8Array(await r.arrayBuffer());if(!b.length)continue;return png(b)?await pdf.embedPng(b):await pdf.embedJpg(b)}catch{}}return null}
function wrapped(page:PDFPage,text:string,x:number,y:number,width:number,font:PDFFont,size:number){const words=text.split(/\s+/).filter(Boolean);let line='',cursor=y;for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)>width&&line){page.drawText(line,{x,y:cursor,size,font,color:DARK});cursor-=size+3;line=word}else line=next}if(line)page.drawText(line,{x,y:cursor,size,font,color:DARK})}
function row(page:PDFPage,label:string,value:unknown,y:number,regular:PDFFont,bold:PDFFont){page.drawText(label,{x:76,y,size:10,font:bold,color:MAROON});wrapped(page,clean(value),235,y,280,regular,10)}
async function build(c:Context,number:string,url:string){const pdf=await PDFDocument.create();const page=pdf.addPage([W,H]);const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const bg=await letterhead(pdf,url);if(bg){const scale=Math.min(W/bg.width,H/bg.height);const width=bg.width*scale,height=bg.height*scale;page.drawImage(bg,{x:(W-width)/2,y:(H-height)/2,width,height})}page.drawText(`Receipt No: ${number}`,{x:76,y:620,size:9,font:regular,color:MUTED});page.drawText(`Date: ${dateText(c.payment.verifiedAt||c.payment.updatedAt)}`,{x:405,y:620,size:9,font:regular,color:DARK});row(page,'Received From',c.owner?.name||c.owner?.email,575,regular,bold);row(page,'Amount',money(c.payment.amountPaise),535,regular,bold);row(page,'Purpose',c.event?.title||c.account?.purpose||c.bill?.category||'Other Payment',495,regular,bold);row(page,'Payment Account',c.account?.displayName,455,regular,bold);row(page,'Payment Method',method(c),415,regular,bold);row(page,'Transaction ID / UTR',transaction(c),375,regular,bold);row(page,'Payment Status','VERIFIED',335,regular,bold);const name=String(c.society?.authorizedSignatory||'').trim();const normalized=name.toLowerCase().replace(/[^a-z]/g,'');if(name&&!new Set(['admin','organizer','adminorganizer','authorizedsignatory','authorisedsignatory']).has(normalized))page.drawText(name,{x:390,y:245,size:10,font:bold,color:MAROON});page.drawText('Authorized Signatory',{x:390,y:231,size:8.5,font:bold,color:MUTED});return pdf.save()}
export async function generateAndStoreReceipt(input:{paymentId:string;societyId:string;requestUrl:string}){const c=await context(input.paymentId,input.societyId);if(!c)throw Error('VERIFIED_PAYMENT_NOT_FOUND');if(c.payment.receiptStoragePath&&c.payment.receiptNumber)return{receiptNumber:c.payment.receiptNumber,receiptStoragePath:c.payment.receiptStoragePath,reused:true};const number=c.payment.receiptNumber||receiptNumber(c.payment.id,c.payment.verifiedAt);const bytes=await build(c,number,input.requestUrl);const path=`${input.societyId}/payment-receipts/${number}.pdf`;await upload(path,bytes);await rest('Payment',{id:`eq.${input.paymentId}`,societyId:`eq.${input.societyId}`,status:'eq.VERIFIED'},{method:'PATCH',body:JSON.stringify({receiptNumber:number,receiptStoragePath:path,receiptGeneratedAt:new Date().toISOString(),updatedAt:new Date().toISOString()})});return{receiptNumber:number,receiptStoragePath:path,reused:false}}
