import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireSubAdminPermission } from '@/lib/session';

async function rest<T>(table:string,q:Record<string,string>={},init?:RequestInit){const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');const u=new URL(b+'/rest/v1/'+table);Object.entries(q).forEach(([a,v])=>u.searchParams.set(a,v));const r=await fetch(u,{...init,headers:{apikey:k,Authorization:'Bearer '+k,Accept:'application/json',...(init?.body?{'Content-Type':'application/json','Prefer':'return=representation'}:{}),...(init?.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error('REST');return d as T}
const bucket=()=>process.env.SUPABASE_STORAGE_BUCKET?.trim()||'society-files';
async function sign(path:string){if(!path||/^https?:\/\//.test(path)||path.startsWith('data:'))return path;const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');const r=await fetch(b+'/storage/v1/object/sign/'+bucket()+'/'+path,{method:'POST',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600}),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw Error('SIGN');return b+'/storage/v1'+(d?.signedURL||d?.signedUrl||'')}
async function remove(path:string){const b=process.env.SUPABASE_URL?.trim().replace(/\/$/,'');const k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!b||!k)throw Error('CONFIG');await fetch(b+'/storage/v1/object/'+bucket(),{method:'DELETE',headers:{apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'},body:JSON.stringify({prefixes:[path]})})}
const schema=z.object({title:z.string().trim().max(180).optional(),altText:z.string().trim().max(180).optional(),albumName:z.string().trim().max(120).optional(),eventId:z.string().trim().min(1).optional(),fileUrl:z.string().trim().min(1)});
export async function GET(){try{const s=await requireSubAdminPermission('GALLERY');const rows=await rest<any[]>('Photo',{select:'*,Event:eventId(title,gujaratiTitle)',societyId:'eq.'+s.societyId,order:'createdAt.desc'});return NextResponse.json({photos:await Promise.all(rows.map(async p=>({...p,fileUrl:p.fileUrl?.startsWith(s.societyId+'/')?await sign(p.fileUrl):null})))});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Forbidden'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:403})}}
export async function POST(req:Request){try{const s=await requireSubAdminPermission('GALLERY');const d=schema.parse(await req.json());if(d.eventId){const event=(await rest<any[]>('Event',{select:'id',id:'eq.'+d.eventId,societyId:'eq.'+s.societyId}))[0];if(!event)return NextResponse.json({error:'Program not found.'},{status:400})}if(!d.fileUrl.startsWith(s.societyId+'/'))return NextResponse.json({error:'Invalid gallery file.'},{status:400});const row=(await rest<any[]>('Photo',{select:'*'},{method:'POST',body:JSON.stringify({id:crypto.randomUUID(),societyId:s.societyId,title:d.title||null,altText:d.altText||null,albumName:d.albumName||null,eventId:d.eventId||null,fileUrl:d.fileUrl,createdAt:new Date().toISOString()})}))[0];return NextResponse.json(row,{status:201})}catch{return NextResponse.json({error:'Invalid gallery request.'},{status:400})}}
export async function DELETE(req:Request){try{const s=await requireSubAdminPermission('GALLERY');const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Photo id is required.'},{status:400});const photo=(await rest<any[]>('Photo',{select:'*',id:'eq.'+id,societyId:'eq.'+s.societyId}))[0];if(!photo)return NextResponse.json({error:'Photo not found.'},{status:404});await rest('Photo',{id:'eq.'+photo.id},{method:'DELETE'});if(photo.fileUrl?.startsWith(s.societyId+'/'))await remove(photo.fileUrl);return NextResponse.json({ok:true})}catch{return NextResponse.json({error:'Unable to remove photo.'},{status:400})}}