'use client';
import {useEffect,useState} from 'react';
import '../globals.css';

type A={id:string;displayName:string;upiId?:string|null;qrImageUrl?:string|null;purpose:string};
type P={id:string;amountPaise:string;status:string;transactionId?:string|null;screenshotUrl?:string|null;expiresAt:string;paymentAccount:{displayName:string;upiId?:string|null;purpose:string;qrImageUrl?:string|null}};
export default function Payments(){const[a,setA]=useState<A[]>([]);const[p,setP]=useState<P[]>([]);const[amount,setAmount]=useState('');const[account,setAccount]=useState('');const[current,setCurrent]=useState<P|null>(null);const[tx,setTx]=useState('');const[shot,setShot]=useState('');const[seconds,setSeconds]=useState(0);const[msg,setMsg]=useState('');
async function load(){const [ar,pr]=await Promise.all([fetch('/api/admin/payment-accounts'),fetch('/api/payments')]);if(ar.ok){const x=await ar.json();setA(x.accounts||[])}if(pr.ok){const x=await pr.json();setP(x.payments||[])}}useEffect(()=>{load()},[]);useEffect(()=>{if(!current)return;const tick=()=>setSeconds(Math.max(0,Math.floor((new Date(current.expiresAt).getTime()-Date.now())/1000)));tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[current]);
async function start(e:React.FormEvent){e.preventDefault();setMsg('');const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentAccountId:account,amountPaise:String(Math.round(Number(amount)*100))})});const x=await r.json();if(!r.ok)return setMsg(x.error||'Unable to start payment');setCurrent({...x.payment,paymentAccount:a.find(v=>v.id===account)||x.payment.paymentAccount});setMsg('Payment session created. Complete the UPI payment and submit the transaction ID.');const selected=a.find(v=>v.id===account);if(selected?.upiId){const uri=`upi://pay?pa=${encodeURIComponent(selected.upiId)}&pn=${encodeURIComponent(selected.displayName)}&am=${encodeURIComponent(amount)}&cu=INR`;window.location.href=uri}}
async function fileData(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024)return setMsg('Screenshot must be under 2 MB.');const r=new FileReader();r.onload=()=>setShot(String(r.result));r.readAsDataURL(f)}
async function submit(){if(!current)return;const r=await fetch('/api/payments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentId:current.id,transactionId:tx,screenshotUrl:shot})});const x=await r.json();if(!r.ok)return setMsg(x.error||'Could not submit');setMsg('Payment evidence submitted. Status will remain Processing until an admin verifies it.');setCurrent(null);setTx('');setShot('');load()}
return <main className="main"><div className="page-title"><div><h1>Society Payments / UPI</h1><p>Pay a published society/program collection and submit proof for verification.</p></div></div><form className="card grid" onSubmit={start}><h2>Make a payment</h2><select className="input" required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select purpose / receiver</option>{a.map(v=><option key={v.id} value={v.id}>{v.purpose} — {v.displayName}</option>)}</select><input className="input" type="number" min="1" step="0.01" placeholder="Amount ₹" required value={amount} onChange={e=>setAmount(e.target.value)}/><button className="btn btn-primary">Pay Now</button></form>{current&&<section className="card"><h2>Payment Processing</h2><p><b>Amount:</b> ₹{(Number(current.amountPaise)/100).toLocaleString('en-IN')}</p><p><b>Time remaining:</b> {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p>{current.paymentAccount.qrImageUrl&&<img src={current.paymentAccount.qrImageUrl} alt="UPI QR" style={{width:240,height:240,objectFit:'contain'}}/>}<p>After completing payment in Google Pay, PhonePe, Paytm or another UPI app, return here.</p><input className="input" placeholder="UPI Transaction ID / UTR" value={tx} onChange={e=>setTx(e.target.value)}/><input className="input" type="file" accept="image/*" onChange={fileData}/>{shot&&<img src={shot} alt="Payment screenshot" style={{maxWidth:300}}/>}<button className="btn btn-primary" disabled={!tx||seconds===0} onClick={submit}>Submit Payment Proof</button></section>}{msg&&<div className="card">{msg}</div>}<section className="grid">{p.map(v=><article className="card" key={v.id}><b>₹{(Number(v.amountPaise)/100).toLocaleString('en-IN')}</b><p>{v.paymentAccount.purpose}</p><p>Status: <b>{v.status==='VERIFIED'?'Payment Success':v.status==='PENDING'?'Payment Processing':v.status}</b></p>{v.transactionId&&<p>Transaction ID: {v.transactionId}</p>}</article>)}</section></main>}
