'use client';
import {useEffect,useMemo,useState} from 'react';
type A={id:string;displayName:string;upiId?:string|null;qrImageUrl?:string|null;purpose:string;instructions?:string|null;amountPaise?:string|null};type P={id:string;amountPaise:string;status:string;transactionId?:string|null;paymentAccount?:A|null};
const statusLabel=(s:string)=>({VERIFIED:'Verified / सफल',PENDING:'Pending verification / जांच बाकी',REJECTED:'Rejected / अस्वीकृत'}[s]||s);
const SESSION_KEY='society_payment_session_v2';
const PAYMENT_WINDOW_MS=5*60*1000;
const actionStyle={width:'100%',minHeight:52,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',padding:'14px 18px',borderRadius:12,fontWeight:600,lineHeight:1.35,whiteSpace:'normal' as const};
export default function Payments(){const[billId,setBillId]=useState('');const[a,setA]=useState<A[]>([]);const[p,setP]=useState<P[]>([]);const[account,setAccount]=useState('');const[current,setCurrent]=useState<any>(null);const[tx,setTx]=useState('');const[shot,setShot]=useState('');const[seconds,setSeconds]=useState(0);const[showProof,setShowProof]=useState(false);const[msg,setMsg]=useState('');
async function load(){try{const[ar,pr]=await Promise.all([fetch('/api/admin/payment-accounts',{cache:'no-store'}),fetch('/api/payments',{cache:'no-store'})]);const[aa,pp]=await Promise.all([ar.json().catch(()=>({})),pr.json().catch(()=>({}))]);if(!ar.ok||!pr.ok)throw Error(aa.error||pp.error||'Unable to load payments.');setA(aa.accounts||[]);setP(pp.payments||[])}catch(e){setMsg(e instanceof Error?e.message:'Unable to load payments.')}}
useEffect(()=>{const q=new URLSearchParams(window.location.search);setBillId(q.get('billId')||'');try{const saved=sessionStorage.getItem(SESSION_KEY);if(saved){const parsed=JSON.parse(saved);if(parsed?.current){const restored={...parsed.current,expiresAt:new Date(parsed.current.expiresAt).getTime()>Date.now()?parsed.current.expiresAt:new Date(Date.now()+PAYMENT_WINDOW_MS).toISOString()};setCurrent(restored);setTx(parsed.tx||'');setShot(parsed.shot||'');setShowProof(Boolean(parsed.showProof));}}}catch{}void load()},[]);
useEffect(()=>{if(!current)return;const expiry=new Date(current.expiresAt).getTime();const tick=()=>setSeconds(Math.max(0,Math.floor((expiry-Date.now())/1000)));tick();const i=setInterval(tick,1000);const onVisible=()=>tick();document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(i);document.removeEventListener('visibilitychange',onVisible)}},[current]);
useEffect(()=>{try{if(current)sessionStorage.setItem(SESSION_KEY,JSON.stringify({current,tx,shot,showProof}));else sessionStorage.removeItem(SESSION_KEY)}catch{}},[current,tx,shot,showProof]);
const selected=useMemo(()=>a.find(x=>x.id===account)||current?.paymentAccount||null,[a,account,current]);const upiUrl=selected?.upiId?`upi://pay?${new URLSearchParams({pa:selected.upiId,pn:selected.displayName,am:(Number(current?.amountPaise||selected.amountPaise||0)/100).toFixed(2),cu:'INR',tn:selected.purpose}).toString()}`:'';
async function start(e:React.FormEvent){e.preventDefault();setMsg('');if(!selected?.amountPaise)return setMsg('This receiver has no fixed amount configured.');const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentAccountId:account,billId:billId||undefined})});const x=await r.json().catch(()=>({}));if(!r.ok)return setMsg(x.error||'Unable to start payment.');setCurrent({...x.payment,amountPaise:String(x.payment.amountPaise),expiresAt:new Date(Date.now()+PAYMENT_WINDOW_MS).toISOString(),paymentAccount:selected});setTx('');setShot('');setShowProof(false);setMsg('Payment session created. Complete payment, then upload proof within 5 minutes.')}
function fileData(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024)return setMsg('Screenshot must be under 5 MB.');if(!['image/jpeg','image/png','image/webp'].includes(f.type))return setMsg('Please select JPG, PNG or WEBP.');const r=new FileReader();r.onload=()=>setShot(typeof r.result==='string'?r.result:'');r.readAsDataURL(f)}
async function submit(){if(!current)return;if(!tx.trim()||!shot)return setMsg('Transaction ID and screenshot are required.');if(!seconds)return setMsg('Payment session expired. Please create a new payment session.');const r=await fetch('/api/payments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentId:current.id,transactionId:tx.trim(),screenshotUrl:shot})});const x=await r.json().catch(()=>({}));if(!r.ok)return setMsg(x.error||'Could not submit proof.');setMsg('Payment proof submitted for verification.');setCurrent(null);await load()}
return <main className="main"><div className="page-title"><div><p className="eyebrow">RESIDENT • PAYMENTS</p><h1>Society Payments / UPI</h1><p>Select a receiver. The amount is fixed by Master Admin and cannot be edited.</p></div></div><form className="card finance-form grid" onSubmit={start}><h2>Make a payment</h2><select className="input" required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select purpose / receiver</option>{a.map(v=><option key={v.id} value={v.id}>{v.purpose} — {v.displayName}</option>)}</select><div className="input" aria-readonly="true">{selected?.amountPaise?`Fixed amount: ₹${(Number(selected.amountPaise)/100).toLocaleString('en-IN')}`:'Select a receiver with a configured amount'}</div><button className="btn btn-primary" style={actionStyle} disabled={!selected?.amountPaise}>Create Payment Session</button></form>{current&&<section className="card"><h2>Complete payment</h2><p><b>Amount:</b> ₹{(Number(current.amountPaise)/100).toLocaleString('en-IN')}</p><p><b>Time remaining:</b> {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p>{selected?.qrImageUrl&&<img src={selected.qrImageUrl} alt="UPI QR" style={{width:240,height:240,objectFit:'contain'}}/>}{selected?.upiId&&<><p><b>UPI ID:</b> {selected.upiId}</p><div style={{width:'100%',maxWidth:420}}><a className="btn btn-primary" style={actionStyle} href={upiUrl}>Open UPI App</a></div></>}{!showProof?<div style={{width:'100%',maxWidth:420,marginTop:12}}><button type="button" className="btn" style={actionStyle} onClick={()=>setShowProof(true)} disabled={seconds<=0}>I completed payment — Upload proof</button></div>:<div className="grid" style={{width:'100%',maxWidth:520}}><input className="input" placeholder="UPI Transaction ID / UTR" value={tx} onChange={e=>setTx(e.target.value)}/><input className="input" type="file" accept="image/jpeg,image/png,image/webp" onChange={fileData}/><button type="button" className="btn btn-primary" style={actionStyle} disabled={!tx.trim()||!shot||seconds<=0} onClick={submit}>Submit Payment Proof</button></div>}</section>}{msg&&<div className="card">{msg}</div>}<section><h2>My Payment History</h2><div className="grid">{p.map(v=><article className="card" key={v.id}><b>₹{(Number(v.amountPaise)/100).toLocaleString('en-IN')}</b><p>{v.paymentAccount?.purpose||'Society payment'}</p><p>Status: <b>{statusLabel(v.status)}</b></p>{v.transactionId&&<p>Transaction ID: {v.transactionId}</p>}</article>)}</div></section></main>}
