'use client';
import { useEffect, useMemo, useState } from 'react';
import { UiIcon } from '@/components/UiIcon';

type Photo={id:string;title?:string|null;altText?:string|null;albumName?:string|null;fileUrl:string};
type Dashboard={photos:Photo[]};

export default function GalleryPage(){
 const [photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[album,setAlbum]=useState('All'),[selected,setSelected]=useState<Photo|null>(null);
 useEffect(()=>{fetch('/api/dashboard').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to load gallery');setPhotos((x as Dashboard).photos||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const albums=useMemo(()=>['All',...Array.from(new Set(photos.map(p=>p.albumName).filter(Boolean) as string[]))],[photos]);
 const visible=useMemo(()=>album==='All'?photos:photos.filter(p=>p.albumName===album),[album,photos]);
 return <main className="main resident-gallery-page">
  <div className="page-title"><div><p className="eyebrow">COMMUNITY • MEMORY</p><h1>Society Gallery / ફોટો ગેલેરી</h1><p>સોસાયટીના કાર્યક્રમો અને યાદગાર ક્ષણો</p></div><span className="page-meta">{photos.length} photos</span></div>
  {error&&<div className="login-error">{error}</div>}
  <section className="card gallery-hero"><div><p className="eyebrow">Madhuli Yuva Group</p><h2>Our Community Moments</h2><p>Browse society memories by album. Tap any photo to view it larger.</p></div><div className="gallery-albums">{albums.map(a=><button key={a} className={'album-chip '+(album===a?'active':'')} onClick={()=>setAlbum(a)}>{a}</button>)}</div></section>
  <section className="section">{loading?<div className="card empty-state">Loading gallery…</div>:visible.length===0?<div className="card empty-state">No gallery photos available.</div>:<div className="resident-gallery-grid">{visible.map((p,i)=><button className="gallery-tile" key={p.id} onClick={()=>setSelected(p)} aria-label={'Open '+(p.title||'society photo')}><img src={p.fileUrl} alt={p.altText||p.title||'Society photo'}/><span className="tile-overlay"><strong>{p.title||'Society memory'}</strong>{p.albumName&&<small>{p.albumName}</small>}</span>{i===0&&<span className="tile-badge">Latest</span>}</button>)}</div>}</section>
  {selected&&<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer" onClick={()=>setSelected(null)}><button className="lightbox-close" onClick={()=>setSelected(null)} aria-label="Close"><UiIcon name="close" size={20}/></button><div className="lightbox-card" onClick={e=>e.stopPropagation()}><img src={selected.fileUrl} alt={selected.altText||selected.title||'Society photo'}/><div className="lightbox-copy"><strong>{selected.title||'Society memory'}</strong>{selected.albumName&&<small>{selected.albumName}</small>}</div></div></div>}
  <style>{".gallery-hero{border-top:3px solid var(--gold);display:flex;justify-content:space-between;gap:20px;align-items:flex-end}.gallery-hero h2{margin:4px 0 5px;color:var(--maroon)}.gallery-hero p:last-child{margin:0;color:var(--muted)}.gallery-albums{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.album-chip{border:1px solid var(--border);background:var(--surface);color:var(--muted);padding:8px 13px;border-radius:999px;cursor:pointer;font:600 12px var(--font-inter),sans-serif}.album-chip.active{background:var(--maroon);border-color:var(--maroon);color:#fff}.resident-gallery-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.gallery-tile{position:relative;padding:0;border:0;border-radius:14px;overflow:hidden;aspect-ratio:4/3;background:var(--soft-surface);cursor:pointer;box-shadow:0 10px 25px rgba(66,19,28,.08)}.gallery-tile img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .4s ease}.gallery-tile:hover img{transform:scale(1.05)}.tile-overlay{position:absolute;left:0;right:0;bottom:0;padding:35px 12px 11px;background:linear-gradient(transparent,rgba(0,0,0,.72));color:#fff;text-align:left;display:flex;flex-direction:column;gap:2px}.tile-overlay strong{font-size:13px}.tile-overlay small{font-size:10px;opacity:.9}.tile-badge{position:absolute;top:10px;right:10px;background:var(--gold);color:var(--maroon);padding:5px 8px;border-radius:999px;font:800 10px var(--font-inter),sans-serif}.gallery-lightbox{position:fixed;inset:0;z-index:1000;background:rgba(24,12,16,.88);display:flex;align-items:center;justify-content:center;padding:24px}.lightbox-card{max-width:min(1000px,94vw);max-height:92vh;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 30px 80px rgba(0,0,0,.35)}.lightbox-card img{display:block;max-width:100%;max-height:78vh;object-fit:contain;background:#111}.lightbox-copy{padding:12px 16px;display:flex;flex-direction:column;gap:3px}.lightbox-copy strong{color:var(--maroon)}.lightbox-copy small{color:var(--muted)}.lightbox-close{position:fixed;top:18px;right:22px;border:0;background:#fff;color:var(--maroon);width:42px;height:42px;border-radius:50%;font-size:28px;cursor:pointer}@media(max-width:1000px){.resident-gallery-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.gallery-hero{align-items:flex-start;flex-direction:column}.gallery-albums{justify-content:flex-start}}@media(max-width:700px){.resident-gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.gallery-tile{border-radius:11px}.gallery-lightbox{padding:12px}.lightbox-card img{max-height:72vh}}@media(max-width:420px){.resident-gallery-grid{grid-template-columns:1fr 1fr}.gallery-hero{padding:16px}.album-chip{padding:7px 10px}}"} </style>
 </main>
}