'use client';
import { useEffect,useState } from 'react';
import { UiIcon } from '@/components/UiIcon';
type Photo={id:string;title?:string|null;altText?:string|null;albumName?:string|null;fileUrl:string;event?:{title:string;gujaratiTitle?:string|null}|null};
export default function GalleryPage(){const [items,setItems]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null);const [form,setForm]=useState({title:'',altText:'',albumName:''});
async function load(){setLoading(true);const r=await fetch('/api/admin/gallery');const x=await r.json();if(r.ok)setItems(Array.isArray(x)?x:[]);else setError(x.error||'Unable to load gallery');setLoading(false)}useEffect(()=>{load()},[]);
async function add(){if(!file){setError('Please choose a photo.');return}setSaving(true);setError('');const fd=new FormData();fd.set('file',file);fd.set('folder','gallery');const up=await fetch('/api/storage/upload',{method:'POST',body:fd});const u=await up.json();if(!up.ok){setError(u.error||'Upload failed.');setSaving(false);return}const r=await fetch('/api/admin/gallery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,fileUrl:u.path})});const x=await r.json();if(!r.ok){setError(x.error||'Unable to save photo.');setSaving(false);return}setItems(v=>[x,...v]);setForm({title:'',altText:'',albumName:''});setFile(null);setSaving(false);const input=document.getElementById('gallery-file') as HTMLInputElement|null;if(input)input.value=''}
async function remove(id:string){if(!confirm('Remove this photo from the gallery?'))return;const r=await fetch('/api/admin/gallery?id='+encodeURIComponent(id),{method:'DELETE'});if(r.ok)setItems(v=>v.filter(x=>x.id!==id));else{const x=await r.json();setError(x.error||'Unable to remove photo.')}}
return <main className="main gallery-page"><div className="page-title"><div><p className="eyebrow">COMMUNITY • GALLERY</p><h1>Gallery / ફોટો ગેલેરી</h1><p>Organize society memories into a clean, responsive photo library.</p></div><button className="btn btn-secondary" onClick={load}><UiIcon name="refresh" size={17}/> Refresh</button></div>{error&&<div className="login-error">{error}</div>}
<section className="card gallery-composer"><div className="section-head"><div><p className="eyebrow">PHOTO UPLOAD</p><h2>Add a society photo</h2></div><span className="page-meta">{items.length} photos</span></div><div className="gallery-form"><div className="field"><label htmlFor="gallery-file">Photo</label><input id="gallery-file" className="input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>JPG, PNG or WEBP • max 5 MB</small></div><div className="field"><label htmlFor="gallery-title">Title</label><input id="gallery-title" className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field"><label htmlFor="gallery-album">Album</label><input id="gallery-album" className="input" value={form.albumName} onChange={e=>setForm({...form,albumName:e.target.value})}/></div><div className="field"><label htmlFor="gallery-alt">Alt text</label><input id="gallery-alt" className="input" value={form.altText} onChange={e=>setForm({...form,altText:e.target.value})}/></div></div><div className="gallery-actions"><button className="btn btn-primary" disabled={saving} onClick={add}>{saving?'Uploading…':'Upload Photo'}</button></div></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">PHOTO LIBRARY</p><h2>Society Gallery</h2></div></div>{loading?<div className="card">Loading…</div>:items.length===0?<div className="card empty-state">No gallery photos yet.</div>:<div className="gallery-admin-grid">{items.map(p=><article className="card gallery-admin-card" key={p.id}><div className="gallery-image-wrap"><img src={p.fileUrl} alt={p.altText||p.title||'Society photo'}/></div><div className="gallery-card-copy"><div><span className="page-meta">{p.albumName||'General'}</span><h3>{p.title||p.event?.gujaratiTitle||p.event?.title||'Society memory'}</h3></div><button className="btn btn-danger" onClick={()=>remove(p.id)}>Remove</button></div></article>)}</div>}</section>
<style>{".gallery-composer{border-top:3px solid var(--gold)}.gallery-form{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:14px}.gallery-actions{display:flex;justify-content:flex-end;margin-top:14px}.gallery-admin-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.gallery-admin-card{overflow:hidden;padding:0}.gallery-image-wrap{aspect-ratio:4/3;background:var(--soft-surface);overflow:hidden}.gallery-image-wrap img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .35s ease}.gallery-admin-card:hover img{transform:scale(1.03)}.gallery-card-copy{padding:14px;display:flex;justify-content:space-between;gap:12px;align-items:flex-end}.gallery-card-copy h3{margin:6px 0 0;color:var(--maroon);font-size:16px}.gallery-card-copy .btn{padding:7px 10px;font-size:12px}@media(max-width:1000px){.gallery-form{grid-template-columns:1fr 1fr}.gallery-admin-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.gallery-form,.gallery-admin-grid{grid-template-columns:1fr}.gallery-actions .btn{width:100%}.gallery-card-copy{align-items:center}}"}</style></main>}